import type { Category } from '../types'

/**
 * Distinctive calendar terms only. Prefer phrases over short ambiguous words.
 * Longer / more specific phrases score higher in the matcher.
 */
export const CATEGORIES_KEYWORDS: Record<
  Exclude<Category, 'uncategorized'>,
  string[]
> = {
  travel: [
    'flight',
    'flights',
    'airport',
    'layover',
    'boarding pass',
    'boarding',
    'departure',
    'arrival',
    'check-in',
    'check in',
    'gate',
    'terminal',
    'vacation',
    'holiday trip',
    'road trip',
    'roadtrip',
    'getaway',
    'sightseeing',
    'backpacking',
    'glamping',
    'staycation',
    'excursion',
    'cruise',
    'hotel',
    'hostel',
    'motel',
    'airbnb',
    'vrbo',
    'resort',
    'cabin',
    'cottage',
    'bed and breakfast',
    'b&b',
    'rental car',
    'car rental',
    'train to',
    'train from',
    'bus tour',
    'luggage',
    'passport',
    'visa appointment',
    'travel',
    'traveling',
    'travelling',
    'trip to',
    'trip from',
    'flying to',
    'flying from',
    'fly to',
    'fly from',
    'fly out',
    'fly home',
    'outbound',
    'return flight',
    'red eye',
    'redeye',
    'uber to airport',
    'lyft to airport',
    'tsa',
    'security checkpoint',
    'baggage',
    'suitcase',
    'packing',
    'itinerary',
    'tour',
    'sightseeing tour',
    'day trip',
    'weekend trip',
    'beach trip',
    'ski trip',
    'camping trip',
    'business trip',
    'work trip',
    'international travel',
    'out of town',
    'out-of-town',
    'away travel',
  ],
  fitness: [
    'gym',
    'workout',
    'work out',
    'workouts',
    'lifting',
    'weightlifting',
    'strength training',
    'bodybuilding',
    'crossfit',
    'hiit',
    'spin class',
    'spinning',
    'peloton',
    'orangetheory',
    'orange theory',
    'f45',
    'soulcycle',
    'barry\'s',
    'yoga',
    'pilates',
    'zumba',
    'aerobics',
    'boxing',
    'kickboxing',
    'mma',
    'martial arts',
    'jiu jitsu',
    'bjj',
    'jogging',
    'morning run',
    'evening run',
    'afternoon run',
    'long run',
    'easy run',
    'tempo run',
    'recovery run',
    'go for a run',
    'go running',
    'went running',
    'trail run',
    'marathon',
    '5k',
    '10k',
    'half marathon',
    'triathlon',
    'cycling',
    'biking',
    'spin ride',
    'swimming',
    'swim practice',
    'swim workout',
    'surfing',
    'hiking',
    'hike',
    'trail hike',
    'climbing',
    'rock climbing',
    'bouldering',
    'pickleball',
    'tennis',
    'basketball',
    'soccer',
    'football practice',
    'volleyball',
    'baseball',
    'softball',
    'hockey',
    'rugby',
    'golf',
    'bowling',
    'rowing',
    'track practice',
    'fitness',
    'personal training',
    'personal trainer',
    'pt session',
    'leg day',
    'arm day',
    'push day',
    'pull day',
    'upper body',
    'lower body',
    'cardio',
    'mobility',
    'stretching',
    'warm up',
    'cool down',
    'lift session',
    'deadlift',
    'squat day',
    'beachbody',
    'barre class',
    'bootcamp',
    'boot camp',
  ],
  social: [
    'birthday',
    'bday',
    'birthday party',
    'housewarming',
    'baby shower',
    'bridal shower',
    'engagement party',
    'wedding',
    'reception',
    'anniversary dinner',
    'reunion',
    'family reunion',
    'friendsgiving',
    'game night',
    'board games',
    'movie night',
    'concert',
    'live music',
    'festival',
    'karaoke',
    'happy hour',
    'hangout',
    'hang out',
    'hanging out',
    'night out',
    'dinner party',
    'dinner with',
    'team dinner',
    'work dinner',
    'client dinner',
    'lunch with',
    'team lunch',
    'brunch with',
    'coffee with',
    'drinks with',
    'drinks at',
    'catch up',
    'catch-up',
    'catchup',
    'potluck',
    'bbq',
    'barbecue',
    'picnic',
    'tailgate',
    'bonfire',
    'celebration',
    'gathering',
    'meetup',
    'meet up',
    'date night',
    'double date',
    'fundraiser',
    'open house',
    'theatre',
    'theater',
    'comedy show',
    'sporting event',
    'watch party',
    'friends',
    'family dinner',
    'family lunch',
    'family visit',
    'visiting friends',
    'visiting family',
    'going out',
    'girls night',
    'guys night',
    'boys night',
    'cocktail',
    'rooftop',
    'trivia night',
    'book club',
  ],
  personal: [
    'doctor',
    "doctor's appointment",
    'doctors appointment',
    'dr appointment',
    'physician',
    'dentist',
    'dental',
    'dental cleaning',
    'orthodontist',
    'optometrist',
    'ophthalmologist',
    'eye exam',
    'dermatologist',
    'derm appointment',
    'therapy',
    'therapist',
    'counseling',
    'counsellor',
    'counselor',
    'physical therapy',
    'physio',
    'chiropractor',
    'chiro',
    'health check',
    'checkup',
    'check-up',
    'annual physical',
    'bloodwork',
    'blood work',
    'lab work',
    'mri',
    'ultrasound',
    'vet',
    'veterinarian',
    'vet appointment',
    'haircut',
    'hair cut',
    'hair appointment',
    'hair salon',
    'barber',
    'nails',
    'manicure',
    'pedicure',
    'spa day',
    'massage',
    'self-care',
    'self care',
    'grocery',
    'groceries',
    'grocery run',
    'costco',
    'trader joe',
    'errand',
    'errands',
    'dry cleaning',
    'laundry',
    'bank appointment',
    'taxes',
    'tax appointment',
    'insurance',
    'lawyer',
    'attorney',
    'dmv',
    'oil change',
    'car maintenance',
    'car service',
    'home repair',
    'plumber',
    'electrician',
    'cleaning service',
    'school pickup',
    'school dropoff',
    'school drop-off',
    'drop-off',
    'pick-up',
    'parent-teacher',
    'parent teacher',
    'homework',
    'study session',
    'volunteer',
    'donation',
    'pharmacy',
    'prescription',
    'meds pickup',
    'medication',
    'dentist appointment',
    'doctor visit',
    'wellness visit',
    'annual checkup',
    'obgyn',
    'ob-gyn',
    'gynecologist',
    'pediatrician',
  ],
}
